use_default_settings: true

search:
  formats:
    - html
    - json

server:
  secret_key: "overridden-by-SEARXNG_SECRET"
  limiter: true

valkey:
  url: valkey://valkey:6379/0

ui:
  static_use_hash: true
